### PR TITLE
get facility call with CWS CMS data, created migrations. fixed 2 bugs…

### PR DESCRIPTION
**Pull request by lavanyareddyreddy**
* Brief feature description

    #142998975- CALS-API update GET facility call - FAS complaints.

* Does this PR block/effect other stories?
    n/a

* Which User story does this relate to?
    n/a

* Do any commands needs to be run in order to run the project with this PR?
    rake db:migrate

* Code coverage percent diff as a result of this PR?
    n/a
* JS errors diff as a result of this PR?
    n/a

### CODE REVIEW

**Comment by lauherkcambria** [comment]
are we dumping this PR?

**Comment by lavanyareddyreddy** [comment]
@keith, I am working on it today.

**Comment by keith** [comment]
Wrong Keith 😄

**Comment by ratneshraval** [comment]
@keith  Still, feel free to work on it!  😄

**Comment by ratneshraval** [comment]
1. strong params are for writing, for read, we shouldn't need them.
2. find is same as find_by_id

**Comment by lauherkcambria** [comment]
@ratneshraval 

1. good point -- I forgot we aren't writing 😅 
2. I got you there! there is a diff: `find` will throw an active record error whereas `find_by_param` will just return nil. 💃

**Comment by ratneshraval** [comment]
Good catch!

**Comment by lavanyareddyreddy** [comment]
@lauherkcambria - As discussed, updated 3rd point with changes. Please review

**Pull request merged**
