### PR TITLE
Add ENV vars in database.yml

### PR DESCRIPTION
**Pull request by lavanyareddyreddy**
* Brief feature description
#143919473
* Does this PR block/effect other stories?
n/a
* Which User story does this relate to?
add env variables to config.
* Do any commands needs to be run in order to run the project with this PR?
n/a
* Code coverage percent diff as a result of this PR?
n/a
* JS errors diff as a result of this PR?
n/a

### CODE REVIEW

**Comment by ratneshraval** [comment]
Please change to DATABASE_USERNAME , DATABASE_PASSWORD.
Also, please update the wiki

**Comment by lavanyareddyreddy** [comment]
@ratneshraval , updated Name and Password to  DATABASE_USERNAME , DATABASE_PASSWORD a and also updated wiki https://github.com/ca-cwds/cals-mock-api/wiki/Environment-Variable

**Comment by ratneshraval** [comment]
Wiki missing host_port. Please add those variables to development section as well.

**Comment by lavanyareddyreddy** [comment]
@ratneshraval updated wiki with host_port.

**Pull request merged**
